name: docker

on:
  push:
    branches: 
    - master

jobs:
  newman-collection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    

    - name: Run newman collection in Docker
      run: |
       docker run -t postman/newman:ubuntu run "https://www.getpostman.com/collections/1ad8115f92f0bffc3089" --reporter-json-export newman-report.json 
    

